SELECT BANCO.NOME AS BANCO,
       AGENCIA.NOME AS AGENCIA,
       CONTA_CORRENTE.NUMERO AS NUM_CONTA,
       CONTA_CORRENTE.DIGITO AS DIGITO,
       CLIENTE.NOME AS CLIENTE,
	   TIPO_TRANSACAO.NOME AS TRANSACAO
FROM BANCO
JOIN AGENCIA ON (AGENCIA.BANCO_NUMERO = BANCO.NUMERO)
JOIN CONTA_CORRENTE ON (CONTA_CORRENTE.BANCO_NUMERO = BANCO.NUMERO 
                   AND CONTA_CORRENTE.AGENCIA_NUMERO = AGENCIA.NUMERO)
JOIN CLIENTE
		   ON (CLIENTE.NUMERO = CONTA_CORRENTE.CLIENTE_NUMERO)
JOIN CLIENTE_TRANSACOES 
          ON (CLIENTE.NUMERO = CLIENTE_TRANSACOES.CLIENTE_NUMERO
		  AND CLIENTE_TRANSACOES.BANCO_NUMERO = BANCO.NUMERO
		  AND CLIENTE_TRANSACOES.AGENCIA_NUMERO = AGENCIA.NUMERO
		  AND CLIENTE_TRANSACOES.CONTA_CORRENTE_NUMERO = CONTA_CORRENTE.NUMERO
		  AND CLIENTE_TRANSACOES.CONTA_CORRENTE_DIGITO = CONTA_CORRENTE.DIGITO)
JOIN TIPO_TRANSACAO 
          ON(CLIENTE_TRANSACOES.TIPO_TRANSACAO_ID = TIPO_TRANSACAO.ID)